### ISSUE TITLE
Published package still contains 'console.log' 

### ISSUE THREAD

**Issue by bySabi** [alvaropinot/circular-iterator#23]
@alvaropinot please update npm

**Comment by alvaropinot** [comment]
Oh! Great catch. I'll take a look ASAP. Thanks @bySabi. 

Just curious here, where or what is the usage of the package for you? :)

**Comment by bySabi** [comment]
Good responsiviness!! :)

I'm using it with the example/demo of [React-Scrollchor](https://github.com/bySabi/react-scrollchor)

here is the lines: https://github.com/bySabi/react-scrollchor/blob/example/src/App.js#L6

Right now I'm making some PR´s for 4.x.x release

**Comment by bySabi** [comment]
and `Saludos desde Alicante` :)

**Comment by alvaropinot** [comment]
saludos desde Dubai, gran tierra la tuya! :D

**Comment by alvaropinot** [comment]
There you have the **v1.1.5** with no `console.log` and with less baggage 😄 

Thank you for the issue 👍 , I'll take a look to your react thingies.

**Comment by bySabi** [comment]
Thanks! Alvaro

Feel free to contact me on my personal email if you needed.
